adding readBySend
HwangWonYo/naver_talk_sdk pull request #40
Opened 2024-10-11 06:50 UTC by tyou0

# Description

Addin readBySend

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2024-10-11 06:51 UTC, tyou0 commented
@hwonyo 

https://github.com/navertalk/chatbot-api/issues/123

2024-10-18 03:55 UTC, hwonyo requested changes
감사합니다. 
테스트 코드까지 추가해주시면 approve 하겠습니다.

2024-10-18 03:55 UTC, hwonyo commented on nta/api.py
> +    def send(self, user_id, message, quick_reply=None, notification=False, read_by_send=False,callback=None):
space 하나 넣어주세요.

```suggestion
    def send(self, user_id, message, quick_reply=None, notification=False, read_by_send=False, callback=None):
```

2024-10-18 03:55 UTC, hwonyo commented on nta/api.py
> +            raise NaverTalkApiError(response)
파일 마지막줄에 빈줄 유지해주세요

2024-10-18 03:55 UTC, hwonyo commented on nta/models/payload.py
> +    def __init__(self, message, quick_reply=None, notification=False,read_by_send=False, **kwargs):
여기도 read_by_send 앞에 space 부탁드립니다.

2024-10-18 03:55 UTC, hwonyo commented on nta/models/payload.py
> +        }
여기도 파일 마지막줄에 빈줄 유지해주세요.

2024-10-20 01:25 UTC, tyou-docenty commented
formatting tool 어떤거 쓰시나요?
 
string 이 어떤건 " 어떤건 ' 를 쓰는데 autoformatting tool 사용하는게 좋을것 같아요.

VScode 에서 md plugin 사용 하면 readme에서 table contents to update 해주는데 table contents가 out of date이라고 나오네요.
[markdown-all-in-one](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)

2024-10-20 04:08 UTC, tyou-docenty commented on nta/api.py
> +    def send(self, user_id, message, quick_reply=None, notification=False, read_by_send=False,callback=None):
Done

2024-10-20 04:08 UTC, tyou-docenty commented on nta/api.py
> +            raise NaverTalkApiError(response)
Done

2024-10-20 04:08 UTC, tyou-docenty commented on nta/models/payload.py
> +    def __init__(self, message, quick_reply=None, notification=False,read_by_send=False, **kwargs):
Done

2024-10-20 04:08 UTC, tyou-docenty commented on nta/models/payload.py
> +        }
Done

2024-10-20 11:00 UTC, hwonyo approved these changes
README 작성까지 감사합니다. 덕분에 오랜만에 업데이트 했네요

2024-10-20 11:01 UTC, hwonyo commented
> formatting tool 어떤거 쓰시나요?
> string 이 어떤건 " 어떤건 ' 를 쓰는데 autoformatting tool 사용하는게 좋을것 같아요.

formatting tool 적용 안 했습니다. 의견 듣고 black으로 적용할까합니다.

> VScode 에서 md plugin 사용 하면 readme에서 table contents to update 해주는데 table contents가 out of date이라고 나오네요. [markdown-all-in-one](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)

감사합니다. md도 확인하고 업데이트하겠습니다.

2024-10-20 11:02 UTC, merged

2024-10-20 11:54 UTC, hwonyo commented
commit 계정이 뭔가 꼬였네요 ㅠ
혹시 추가 의견 주신 부분도 작성해주신다면 기다리겠습니다

2024-10-21 09:26 UTC, tyou0 commented
아 워낙에 잘쓰셔서 저도 편하게 잘 만들었어요
혹시 오픈 소스나 다른 프로젝트 있으면 함 같이 만들어요 좀 배우고 싶네요

2024-10-23 04:40 UTC, tyou0 commented
@hwonyo 아 버전업해서 pip에 올려주세요

2024-10-24 22:59 UTC, hwonyo commented
@tyou0 1.0.6으로 버전업했습니다

> 아 워낙에 잘쓰셔서 저도 편하게 잘 만들었어요 혹시 오픈 소스나 다른 프로젝트 있으면 함 같이 만들어요 좀 배우고 싶네요

좋습니다 ㅎㅎ 요즘 개인적으로 진행하는건 없어서 뭔가 생기면 같이 해보시죠. 
링크드인 하시면 연락주세요. [linkedin](https://www.linkedin.com/in/wonyo-hwang-a5645615a)